const menuCategories = [
  { id: 'breakfast', name: 'Завтраки' },
  { id: 'raw', name: 'Raw' },
  { id: 'cold', name: 'Холодные закуски' },
  { id: 'bruschetta', name: 'Брускетты' },
  { id: 'wine', name: 'К вину' },
  { id: 'salads', name: 'Салаты' },
  { id: 'soups', name: 'Супы' },
  { id: 'pasta', name: 'Паста и ризотто' },
  { id: 'meat', name: 'Мясо' },
  { id: 'fish', name: 'Рыба' },
  { id: 'grill', name: 'Grill' },
  { id: 'mangal', name: 'Мангал' },
  { id: 'sides', name: 'Гарниры' },
];

function createMenuItem(id, category, title, price, priceFrom = false, weight = '300 грамм') {
  return {
    id,
    category,
    title,
    price,
    priceFrom,
    weight,
    image: `https://picsum.photos/seed/food-${id}/400/400`,
    thumbnails: [
      `https://picsum.photos/seed/food-${id}a/120/120`,
      `https://picsum.photos/seed/food-${id}b/120/120`,
      `https://picsum.photos/seed/food-${id}c/120/120`,
    ],
    addons: [
      { id: 1, titleKey: 'addon.extra', price: 150 },
      { id: 2, titleKey: 'addon.sauce', price: 80 },
    ],
  };
}

const menuItems = [
  {
    id: 1,
    category: 'breakfast',
    title: 'Яичница-глазунья из трех яиц',
    price: 250,
    priceFrom: false,
    weight: '400 грамм',
    image: "./images/data-image/trex.png",
    thumbnails: [
      'https://picsum.photos/seed/food-1a/120/120',
      'https://picsum.photos/seed/food-1b/120/120',
      'https://picsum.photos/seed/food-1c/120/120',
    ],
    addons: [
      { id: 1, titleKey: 'addon.shrimp', price: 450 },
      { id: 2, titleKey: 'addon.tomatoes', price: 80 },
      { id: 3, titleKey: 'addon.bacon', price: 120 },
      { id: 4, titleKey: 'addon.cheddar', price: 80 },
    ],
  },
  {
    id: 2,
    category: 'breakfast',
    title: 'Омлет из трех яиц',
    price: 250,
    priceFrom: false,
    weight: '350 грамм',
    image: './images/data-image/yaits.png',
    thumbnails: [
      'https://picsum.photos/seed/food-2a/120/120',
      'https://picsum.photos/seed/food-2b/120/120',
      'https://picsum.photos/seed/food-2c/120/120',
    ],
    addons: [
      { id: 1, titleKey: 'addon.shrimp', price: 450 },
      { id: 2, titleKey: 'addon.tomatoes', price: 80 },
      { id: 3, titleKey: 'addon.bacon', price: 120 },
      { id: 4, titleKey: 'addon.cheddar', price: 80 },
    ],
  },
  {
    id: 3,
    category: 'breakfast',
    title: 'Домашние сырники',
    price: 490,
    priceFrom: false,
    weight: '300 грамм',
    image: './images/data-image/sirniki.png',
    thumbnails: [
      'https://picsum.photos/seed/food-3a/120/120',
      'https://picsum.photos/seed/food-3b/120/120',
      'https://picsum.photos/seed/food-3c/120/120',
    ],
    addons: [
      { id: 1, titleKey: 'addon.sourcream', price: 60 },
      { id: 2, titleKey: 'addon.jam', price: 80 },
      { id: 3, titleKey: 'addon.honey', price: 70 },
    ],
  },
  {
    id: 4,
    category: 'breakfast',
    title: 'Блины',
    price: 190,
    priceFrom: true,
    weight: '250 грамм',
    image: './images/data-image/Pancakes.png',
    thumbnails: [
      'https://picsum.photos/seed/food-4a/120/120',
      'https://picsum.photos/seed/food-4b/120/120',
      'https://picsum.photos/seed/food-4c/120/120',
    ],
    addons: [
      { id: 1, titleKey: 'addon.sourcream', price: 60 },
      { id: 2, titleKey: 'addon.caviar', price: 350 },
      { id: 3, titleKey: 'addon.salmon', price: 280 },
    ],
  },
  {
    id: 5,
    category: 'breakfast',
    title: 'Каша с ягодами и кедровыми орехами',
    price: 450,
    priceFrom: false,
    weight: '350 грамм',
    image: './images/data-image/Porridge.png',
    thumbnails: [
      'https://picsum.photos/seed/food-5a/120/120',
      'https://picsum.photos/seed/food-5b/120/120',
      'https://picsum.photos/seed/food-5c/120/120',
    ],
    addons: [
      { id: 1, titleKey: 'addon.honey', price: 70 },
      { id: 2, titleKey: 'addon.cream', price: 50 },
    ],
  },
  {
    id: 6,
    category: 'breakfast',
    title: 'Скрэмбл',
    price: 290,
    priceFrom: false,
    weight: '300 грамм',
    image: './images/data-image/Scramble.png',
    thumbnails: [
      'https://picsum.photos/seed/food-6a/120/120',
      'https://picsum.photos/seed/food-6b/120/120',
      'https://picsum.photos/seed/food-6c/120/120',
    ],
    addons: [
      { id: 1, titleKey: 'addon.bacon', price: 120 },
      { id: 2, titleKey: 'addon.cheddar', price: 80 },
    ],
  },
  {
    id: 7,
    category: 'breakfast',
    title: 'Яйцо Бенедикт с лососем',
    price: 850,
    priceFrom: false,
    weight: '400 грамм',
    image: './images/data-image/Benedict.png',
    thumbnails: [
      'https://picsum.photos/seed/food-7a/120/120',
      'https://picsum.photos/seed/food-7b/120/120',
      'https://picsum.photos/seed/food-7c/120/120',
    ],
    addons: [
      { id: 1, titleKey: 'addon.avocado', price: 150 },
      { id: 2, titleKey: 'addon.shrimp', price: 450 },
    ],
  },
  {
    id: 8,
    category: 'breakfast',
    title: 'Яйцо Бенедикт с беконом',
    price: 650,
    priceFrom: false,
    weight: '400 грамм',
    image: './images/data-image/bacon.png',
    thumbnails: [
      'https://picsum.photos/seed/food-8a/120/120',
      'https://picsum.photos/seed/food-8b/120/120',
      'https://picsum.photos/seed/food-8c/120/120',
    ],
    addons: [
      { id: 1, titleKey: 'addon.avocado', price: 150 },
      { id: 2, titleKey: 'addon.cheddar', price: 80 },
    ],
  },
  {
    id: 9,
    category: 'breakfast',
    title: 'Гречневая каша с авокадо, яйцом пашот и пармезаном',
    price: 490,
    priceFrom: false,
    weight: '380 грамм',
    image: './images/data-image/trex.png',
    thumbnails: [
      'https://picsum.photos/seed/food-9a/120/120',
      'https://picsum.photos/seed/food-9b/120/120',
      'https://picsum.photos/seed/food-9c/120/120',
    ],
    addons: [
      { id: 1, titleKey: 'addon.salmon', price: 280 },
      { id: 2, titleKey: 'addon.parmesan', price: 90 },
    ],
  },
  {
    id: 10,
    category: 'breakfast',
    title: 'Кобб – салат с лососем',
    price: 890,
    priceFrom: false,
    weight: '350 грамм',
    image: './images/data-image/Salad.png',
    thumbnails: [
      'https://picsum.photos/seed/food-10a/120/120',
      'https://picsum.photos/seed/food-10b/120/120',
      'https://picsum.photos/seed/food-10c/120/120',
    ],
    addons: [
      { id: 1, titleKey: 'addon.avocado', price: 150 },
      { id: 2, titleKey: 'addon.poachedEgg', price: 80 },
    ],
  },
  {
    id: 11,
    category: 'breakfast',
    title: 'Кобб – салат с креветками',
    price: 960,
    priceFrom: false,
    weight: '350 грамм',
    image: './images/data-image/Salad.png',
    thumbnails: [
      'https://picsum.photos/seed/food-11a/120/120',
      'https://picsum.photos/seed/food-11b/120/120',
      'https://picsum.photos/seed/food-11c/120/120',
    ],
    addons: [
      { id: 1, titleKey: 'addon.shrimp', price: 450 },
      { id: 2, titleKey: 'addon.avocado', price: 150 },
    ],
  },
  createMenuItem(12, 'raw', 'Тартар из говядины', 890),
  createMenuItem(13, 'raw', 'Тартар из лосося', 950),
  createMenuItem(14, 'raw', 'Карпаччо из телятины', 780),
  createMenuItem(15, 'cold', 'Ассорти из сыров', 690),
  createMenuItem(16, 'cold', 'Оливки и марinated овощи', 420),
  createMenuItem(17, 'cold', 'Мясное ассорти', 850),
  createMenuItem(18, 'bruschetta', 'Брускетта с томатами', 320),
  createMenuItem(19, 'bruschetta', 'Брускетта с лососем', 490),
  createMenuItem(20, 'bruschetta', 'Брускетта с ветчиной', 450),
  createMenuItem(21, 'wine', 'Сырная тарелка к вину', 890),
  createMenuItem(22, 'wine', 'Мясное ассорти к вину', 960),
  createMenuItem(23, 'wine', 'Оливки и орехи', 380),
  createMenuItem(24, 'salads', 'Цезарь с курицей', 590),
  createMenuItem(25, 'salads', 'Греческий салат', 520),
  createMenuItem(26, 'salads', 'Салат с креветками', 780),
  createMenuItem(27, 'soups', 'Борщ', 390),
  createMenuItem(28, 'soups', 'Том ям с креветками', 650),
  createMenuItem(29, 'soups', 'Крем-суп из грибов', 420),
  createMenuItem(30, 'pasta', 'Карбонара', 690),
  createMenuItem(31, 'pasta', 'Ризотто с грибами', 720),
  createMenuItem(32, 'pasta', 'Паста с морепродуктами', 890),
  createMenuItem(33, 'meat', 'Стейк рибай', 1890),
  createMenuItem(34, 'meat', 'Телячья отбивная', 980),
  createMenuItem(35, 'meat', 'Баранья корейка', 1450),
  createMenuItem(36, 'fish', 'Лосось на гриле', 1250),
  createMenuItem(37, 'fish', 'Дорадо запечённая', 1180),
  createMenuItem(38, 'fish', 'Креветки темпура', 890),
  createMenuItem(39, 'grill', 'Куриные крылышки', 590),
  createMenuItem(40, 'grill', 'Свиные ребрышки', 890),
  createMenuItem(41, 'grill', 'Овощи на гриле', 450),
  createMenuItem(42, 'mangal', 'Шашлык из баранины', 890),
  createMenuItem(43, 'mangal', 'Люля-кебаб', 650),
  createMenuItem(44, 'mangal', 'Овощи на мангале', 420),
  createMenuItem(45, 'sides', 'Картофель фри', 290),
  createMenuItem(46, 'sides', 'Рис с овощами', 320),
  createMenuItem(47, 'sides', 'Пюре из трюфельного картофеля', 390),
];
